---
apiVersion: v1
kind: Service
metadata:
  name: carrier
  namespace: aviary
  labels:
    app: carrier
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: carrier

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrier
  namespace: aviary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carrier
      version: v1
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: aviary
        appmesh.k8s.aws/virtualNode: carrier-v1-aviary
      labels:
        app: carrier
        version: v1
    spec:
      serviceAccountName: aviary-pods
      securityContext:
        fsGroup: 1337
      containers:
        - name: carrier
          image: bcelenza/carrier
          ports:
            - containerPort: 80
          env:
            - name: "HTTP_PORT"
              value: "80"

---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: carrier-v1
  namespace: aviary
spec:
  meshName: aviary
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostName: carrier.aviary.svc.cluster.local
  backends:
    - virtualService:
        virtualServiceName: mockingbird.aviary.svc.cluster.local
  logging:
    accessLog:
      file:
        path: /dev/stdout

