---
apiVersion: v1
kind: Service
metadata:
  name: cuckoo
  namespace: aviary
  labels:
    app: cuckoo
spec:
  ports:
    - port: 22
      name: ssh
    - port: 9901
      name: envoy-admin
  selector:
    app: cuckoo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuckoo
  namespace: aviary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cuckoo
      version: v1
  template:
    metadata:
      labels:
        app: cuckoo
        version: v1
    spec:
      serviceAccountName: aviary-pods
      securityContext:
        fsGroup: 1337
      containers:
        - name: usurper
          image: bcelenza/usurper
          ports:
            - containerPort: 22

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: cuckoo-v1
  namespace: aviary
spec:
  podSelector:
    matchLabels:
      app: cuckoo
      version: v1
  backends:
    - virtualService:
        virtualServiceRef:
          name: mockingbird
    - virtualService:
        virtualServiceRef:
          name: dipper-client
  listeners:
  - portMapping:
      port: 22
      protocol: tcp
  serviceDiscovery:
    dns:
      hostname: cuckoo.aviary.svc.cluster.local
  backendDefaults:
    clientPolicy:
      tls:
        validation:
          trust:
            acm:
              certificateAuthorityARNs:
                - arn:aws:acm-pca:us-east-1:027496699299:certificate-authority/ce980227-0739-492d-a3be-589a924fbb31
  logging:
    accessLog:
      file:
        path: /dev/stdout

