---
apiVersion: v1
kind: Service
metadata:
  name: dipper-server
  namespace: aviary
  labels:
    app: dipper-server
spec:
  ports:
    - port: 8080
      name: grpc
    - port: 9901
      name: envoy-admin
  selector:
    app: dipper-server
    version: v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dipper-server
  namespace: aviary
spec:
  replicas: 10
  selector:
    matchLabels:
      app: dipper-server
      version: v1
  template:
    metadata:
      labels:
        app: dipper-server
        version: v1
    spec:
      serviceAccountName: aviary-pods
      securityContext:
        fsGroup: 1337
      containers:
        - name: dipper-server
          image: bcelenza/dipper-server
          ports:
            - containerPort: 8080
          env:
            - name: "PORT"
              value: "8080"
            - name: "COLOR"
              value: "no color!"

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: dipper-server-v1
  namespace: aviary
spec:
  podSelector:
    matchLabels:
      app: dipper-server
      version: v1
  listeners:
    - portMapping:
        port: 8080
        protocol: grpc
      healthCheck:
        protocol: grpc
        path: /ping
        healthyThreshold: 2
        unhealthyThreshold: 10
        timeoutMillis: 2000
        intervalMillis: 5000
      tls:
        mode: STRICT
        certificate:
          acm:
            certificateARN: arn:aws:acm:us-east-1:027496699299:certificate/8da4ee1e-a0ec-437b-9629-edfbe10097cf
  serviceDiscovery:
    dns:
      hostname: dipper-server.aviary.svc.cluster.local

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: dipper-server
  namespace: aviary
spec:
  awsName: dipper-server.aviary.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: dipper-server
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: dipper-server
  namespace: aviary
spec:
  listeners:
    - portMapping:
        port: 8080
        protocol: grpc
  routes:
    - name: dipper-server-route
      grpcRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef: 
                name: dipper-server-v1
              weight: 1