---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    mesh: aviary
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
  name: aviary
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: aviary
spec:
  namespaceSelector:
    matchLabels:
      mesh: aviary