---
apiVersion: v1
kind: Service
metadata:
  name: mockingbird
  namespace: aviary
  labels:
    app: mockingbird
spec:
  ports:
    - port: 80
      name: http
    - port: 9901
      name: envoy-admin
  selector:
    app: mockingbird
    version: v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockingbird
  namespace: aviary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockingbird
      version: v1
  template:
    metadata:
      labels:
        app: mockingbird
        version: v1
    spec:
      serviceAccountName: aviary-pods
      securityContext:
        fsGroup: 1337
      containers:
        - name: mockingbird
          image: bcelenza/mockingbird
          ports:
            - containerPort: 80
          env:
            - name: "HTTP_PORT"
              value: "80"

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: mockingbird-v1
  namespace: aviary
spec:
  podSelector:
    matchLabels:
      app: mockingbird
      version: v1
  listeners:
    - portMapping:
        port: 80
        protocol: http
      tls:
        mode: STRICT
        certificate:
          acm:
            certificateARN: arn:aws:acm:us-east-1:027496699299:certificate/8da4ee1e-a0ec-437b-9629-edfbe10097cf
  serviceDiscovery:
    dns:
      hostname: mockingbird.aviary.svc.cluster.local

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: mockingbird
  namespace: aviary
spec:
  awsName: mockingbird.aviary.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: mockingbird
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: mockingbird
  namespace: aviary
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
  routes:
    - name: mockingbird-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef: 
                name: mockingbird-v1
              weight: 1
        retryPolicy:
          maxRetries: 4
          perRetryTimeout:
            value: 1
            unit: s
          httpRetryEvents:
          - server-error
          tcpRetryEvents:
          - connection-error