---
apiVersion: v1
kind: Service
metadata:
  name: mockingbird
  namespace: aviary
  labels:
    app: mockingbird
spec:
  ports:
    - port: 80
      name: http
    - port: 9901
      name: envoy-admin
  selector:
    app: mockingbird
    version: v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockingbird
  namespace: aviary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mockingbird
      version: v1
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: aviary
        appmesh.k8s.aws/virtualNode: mockingbird-v1-aviary
      labels:
        app: mockingbird
        version: v1
    spec:
      serviceAccountName: aviary-pods
      securityContext:
        fsGroup: 1337
      containers:
        - name: mockingbird
          image: bcelenza/mockingbird
          ports:
            - containerPort: 80
          env:
            - name: "HTTP_PORT"
              value: "80"

---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: mockingbird-v1
  namespace: aviary
spec:
  meshName: aviary
  listeners:
    - portMapping:
        port: 80
        protocol: http
      tls:
        mode: STRICT
        certificate:
          acm:
            certificateArn: arn:aws:acm:us-east-1:027496699299:certificate/8da4ee1e-a0ec-437b-9629-edfbe10097cf
  serviceDiscovery:
    dns:
      hostName: mockingbird.aviary.svc.cluster.local

---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: mockingbird.aviary.svc.cluster.local
  namespace: aviary
spec:
  meshName: aviary
  virtualRouter:
    listeners:
      - portMapping:
          port: 80
          protocol: http
  routes:
    - name: default-route
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: mockingbird-v1
              weight: 1
        retryPolicy:
          maxRetries: 4
          perRetryTimeoutMillis: 1000
          httpRetryEvents:
          - server-error