apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-controller
  namespace: appmesh-system
  annotations:
    app.kubernetes.io/name: external-dns-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: external-dns-controller
  name: external-dns-controller
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-controller
subjects:
- kind: ServiceAccount
  name: external-dns-controller
  namespace: appmesh-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-controller
  namespace: appmesh-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-controller
  template:
    metadata:
      labels:
        app: external-dns-controller
    spec:
      serviceAccountName: external-dns-controller
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=celenza.dev # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
        - --registry=txt
        - --txt-owner-id=Z7XA9CYFFEII1
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files