apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aviary
  region: us-east-1

nodeGroups:
  - name: appmesh-system
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 10
    privateNetworking: true
    iam:
      attachPolicyArns:
        - arn:aws:iam::aws:policy/AWSCertificateManagerPrivateCAReadOnly
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true